const express = require('express'); 
const router = express.Router(); 
const { register, login, getProfile, updateProfile } = require('../controllers/auth.controller'); 
const { authenticateToken } = require('../middleware/auth'); 
router.post('/signup', register); 
router.post('/login', login); 
router.post('/signin', login); 
router.get('/profile', authenticateToken, getProfile); 
router.put('/profile', authenticateToken, updateProfile); 
module.exports = router;